### ISSUE TITLE
User Story: Get Estimates for Green Tech on their Property

### ISSUE THREAD

**Issue by austina-lin** [ryan-bradford/Capsol-API#11]
As a homeowner, I need to receive and view estimates on each green technology's benefits/returns on their property so that I can accurately gauge my interest.

**Additional context**

**Comment by ryan-bradford** [comment]
This is for the most part done. 
Missing features:
1. Check electricity price in the address.
2. Check usable space on the homeowners roof.
3. Check general productivity of solar in the area (I.E. amount of sunlight).
